### ISSUE TITLE
Question: Sync from some point, not from genesis?

### ISSUE THREAD

**Issue by Head** [mappum/blockchain-download#2]
I've tried to sync from a given block with:
`
            paramsBlockchain.genesisHeader = {
                version: 536870912,
                prevHash: reverse(new Buffer('00000000a11fabc50afe39d14cd80111e3e96cbbec533b213a849d35d7c8b7f6', 'hex')),
                merkleRoot: u.toHash('69eeff60b3868a6c21bedb83148839e3349127be7dc074487fc6b833ba94c951'),
                timestamp: 1296688602,
                bits: 486604799,
                nonce: 2417625878
            };`
But I got an "Block does not connect to chain" error. Yes, the prevHash is not in the db. Do I really need to sync ALL blocks? I just wanna sync from that point where the user entered my system.

**Comment by mappum** [comment]
You should be able to do this via `paramsBlockchain.checkpoints = [ { version: 536870912, ... } ]`.

Thanks for the issue, there should probably be a better API for this and clearer documentation.

**Comment by Head** [comment]
What checkpoints are valid? When I try height 153216 in testnet it works, but not with 153217. It say: " Key not found in database"

**Comment by Head** [comment]
heigth/2016!
